drop table if exists statistics cascade;

CREATE TABLE IF NOT EXISTS statistics
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(64),
    uri       VARCHAR(64),
    ip        VARCHAR(64),
    timestamp TIMESTAMP
);
